### ISSUE TITLE
Propuesta diseño

### ISSUE THREAD

**Issue by AlexiaCaride** [dwcs-ucha/grupo02-21#1]
[https://balsamiq.cloud/sk9ldit/pqkcqpe](url)
Esta es mi propuesta para el diseño, la idea sería utilizar como página principal una página con los enlaces a las calculadoras, o el proyecto individual de cada uno, o por el contrario utilizar el apartado de Novas que sería el CMS. La barra de menú tiene los enlaces de ejemplo porque aun no se que páginas va a haber en total

**Comment by maikol-ortigueira** [comment]
A mi me parece bien

**Comment by JorgeCM00** [comment]
A mi tambien me gusta así

**Comment by OscarCPC** [comment]
Tiene muy buena pinta :)

**Comment by maikol-ortigueira** [comment]
Una pregunta @AlexiaCaride  ¿que versión vamos a utilizar de bootstrap?

**Comment by AlexiaCaride** [comment]
Estoy utilizando la 5 @maikol-ortigueira , si prefieres usar otra me da igual aprender una que otra

**Comment by maikol-ortigueira** [comment]
Me da lo mismo, simplemente quería saberlo para no tener después que cambiar las clases.
Por mi perfecto v-5

**Comment by maikol-ortigueira** [comment]
Queda aprobado el diseño propuesto por @AlexiaCaride
