### ISSUE TITLE
Incidencia Ckfinder (para Marcos)

### ISSUE THREAD

**Issue by JorgeCM00** [dwcs-ucha/grupo02-21#15]
Llamada  al script 

`<script type="text/javascript">
        //Esto la llamada al script de cskjeditor para la modificación del textarea
        ClassicEditor
                .create(document.querySelector('#editor'), { 
                ckfinder: {
			uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
                 
		},
                    } )
                    .catch( error => {
		console.error( error );
                } )
                .then(editor => {
                    window.editor = editor;
                })
                .catch(err => {
                    console.error(err.stack);
                });
    </script>`

Capturas:
![Captura de pantalla (12)](https://user-images.githubusercontent.com/94856015/145677220-6e1fe2bd-165c-4b7e-80ce-2681b4bc2e8d.png)

En cuanto acepto el alert la imagen desaparece

PD: No sé porqué el codigo aparece así pero no lo doy cambiado, es desde que se abre hasta que se cierra la etiqueta <script>

**Comment by dwcs-ucha** [comment]
Ola,

Comprobaches os permisos? Ten que haber un cartafol upload ou similar debe ser tempDirectory onde teña acceso de escritura www-data, chmod 0777.

Tes aquí a información para Windows:

https://ckeditor.com/docs/ckfinder/ckfinder3-php/quickstart.html

Revisa eses pasos. Ollo que tamén pide algunha librería de PHP específica, podes ver se está no servidor cun phpinfo.php.

Saúdos.
