### ISSUE TITLE
Validaciones

### ISSUE THREAD

**Issue by JorgeCM00** [dwcs-ucha/grupo02-21#3]
Buenas compañeros, para las validaciones como va el tema?

**Comment by LuckyLewis** [comment]
Las llevo yo. ¿Qué necesitas?

**Comment by JorgeCM00** [comment]
Nada, una que permita solo texto pero entiendo que tengo que usar las que haces tu, en clase me explicas como hacer para utilizarlas porfa?

**Comment by LuckyLewis** [comment]
Sin problema, es más sencillo de lo que parece. Si hace falta, incluso miramos de hacer una que se adecúe a lo que necesites porque creo que no tengo ninguna para texto largo, por ejemplo.

Luego miramos.

**Comment by JorgeCM00** [comment]
Perfecto, thank you!!!
