### ISSUE TITLE
Escritura de fichero para el archivo de log

### ISSUE THREAD

**Issue by LuckyLewis** [dwcs-ucha/grupo02-21#5]
Sería interesante, @rdn998, buscar un modo de escribir el fichero únicamente añadiendo una línea al final del mismo, sin necesidad de leerlo.

Y quizás, lo que comentaba Marcos, podría ser interesante plantear un modo de diferenciar un error de un registro rutinario, ya sea mediante parámetro o tomando el principio de la cadena de texto como refernecia, en cuyo caso debería devolvérsele al usuario a modo de aviso.

Pero bueno, first things first, escribir el fichero y el resto vamos viendo.

**Comment by rdn998** [comment]
Me parece bien.
Ya he creado el objeto Log, el cual recogerá los logs del usuario dependiendo de su tipo, fatal, warning y log normal.
Los métodos serían fatalLog(), para añadir logs de errores fatales, warningLog(), para añadir logs de errores de aviso y logs, para añadir los logs normales

**Comment by LuckyLewis** [comment]
En [este enlace](https://www.javatpoint.com/php-append-to-file) parece haber un modo de hacer el 'append' en un fichero.

La clase Log está bien aunque pienso yo que quitaría los fatalErrors nada más.

**Comment by rdn998** [comment]
Muchas gracias por el enlace, en cuánto acabe con lo que estoy haciendo lo implemento

**Comment by LuckyLewis** [comment]
Estaría súper bien que cada vez que escribiera en el archivo de log hiciera un salto de línea. Por lo que he podido comprobar, con el uso de "\n" entre comillas dobles sería suficiente. Desgraciadamente, las comillas simples, las de ejecución, las españolas, y los acentos oblícuos no sirven en este caso.

**Comment by rdn998** [comment]
Llega usted tarde, en el momento que ha puesto este comentario ya hemos actualizado nuestro código para que hiciera los saltos de línea. Pero muchísimas gracias por su aporte.

**Comment by LuckyLewis** [comment]
Qué detalle, ahora está súper bien. Gracias.
