### ISSUE TITLE
Escritura de ficheros desde dos clientes al mismo tiempo

### ISSUE THREAD

**Issue by LuckyLewis** [dwcs-ucha/grupo02-21#7]
Revisando la escritura del fichero de log con @rdn998, hemos caído en la cuenta de que podría darse el caso en que dos clientes trataran de escribir en el fichero al mismo tiempo y que, en caso de que eso no fuera posible, podría perderse uno de los registros.

Aún estamos haciendo pruebas, ¿pero es esto un problema? ¿Deberíamos controlar que no se intente acceder desde dos lugares al mismo tiempo?

**Comment by dwcs-ucha** [comment]
Ola,

Ao ser ficheiros pequenos e ter poucos usuarios e moi improbable que aconteza. Este tipo de controis quedarían para as bases de datos cando as incorporemos.

Un saúdo.

**Comment by LuckyLewis** [comment]
Ok, nos despreocupamos pues. Le acabas de dar una alegría a @rdn998.

**Comment by dwcs-ucha** [comment]
Só por curiosidade, habería que tirar por aquí:

https://www.php.net/manual/es/splfileobject.flock.php

Repito, só por que vos quede a idea. ;-)

Saúdos.
